// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' as firebase_core;

class DefaultFirebaseOptions {
  static firebase_core.FirebaseOptions get currentPlatform {
    return const firebase_core.FirebaseOptions(
      apiKey: 'dummy-api-key',
      appId: '1:956047851248:android:90791037477555804b4c35',
      messagingSenderId: '956047851248',
      projectId: 'nibq-app',
      storageBucket: 'nibq-app.appspot.com',
    );
  }
}
